site_name: FastCFS Docs
site_description:  'FastCFS Documents,Version: v3.2.0'

repo_name: GitHub
repo_url: https://github.com/happyfish100/FastCFS/

plugins:
  - search
  - mike:
      version_selector: true
nav:
  - Introduction:
    - FastCFS Introduction: "index.md"
    - Release Notes: "ReleaseNotes.md"
    - Benchmarks: "benchmark.md"
  - Concepts:
    - Architecture:
        - FastDir: "concepts/fastDir.md"
        - FastStore: "concepts/fast-store.md"
        - FastAuth: "concepts/fastDir.md"
  - UserGuide:
      - Quickstart: "Easy-install-detail-zh_CN.md"
      - Install: "INSTALL.md"

markdown_extensions:
  - toc:
      permalink: True
  - footnotes
  - tables
  - meta  # 定义元数据，通过文章上下文控制，如disqus
  - pymdownx.caret  # 下划线上标
  - pymdownx.tilde  # 删除线下标
  - pymdownx.critic  # 增加删除修改高亮注释，可修饰行内或段落
  - pymdownx.details  # 提示块可折叠
  - pymdownx.inlinehilite  # 行内代码高亮
  - pymdownx.mark  # 文本高亮
  - pymdownx.smartsymbols  # 符号转换
  - pymdownx.superfences  # 代码嵌套在列表里
  - codehilite:    # 代码高亮，显示行号
      guess_lang: false
      linenums: true
  - pymdownx.tasklist:  # 复选框checklist
      custom_checkbox: true

theme:
  name: material
  logo: img/logo.png
  favicon: img/logo.png
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: deep orange
      accent: deep orange
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
extra:
  version:
    provider: mike
  alternate:
    - name: English
      link: /
      lang: en
    - name: 中文
      link: /zh/
      lang: zh

